#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS = \
$(OUTDIR)\.\FileFormat\AVSField\AVSField.obj \
$(OUTDIR)\.\FileFormat\AVSUCD\AVSUcd.obj \
$(OUTDIR)\.\FileFormat\BMP\Bmp.obj \
$(OUTDIR)\.\FileFormat\BMP\FileHeader.obj \
$(OUTDIR)\.\FileFormat\BMP\InfoHeader.obj \
$(OUTDIR)\.\FileFormat\CSV\Csv.obj \
$(OUTDIR)\.\FileFormat\DICOM\Attribute.obj \
$(OUTDIR)\.\FileFormat\DICOM\Dicom.obj \
$(OUTDIR)\.\FileFormat\DICOM\DicomList.obj \
$(OUTDIR)\.\FileFormat\DICOM\Element.obj \
$(OUTDIR)\.\FileFormat\DICOM\Item.obj \
$(OUTDIR)\.\FileFormat\DICOM\Tag.obj \
$(OUTDIR)\.\FileFormat\DICOM\VR.obj \
$(OUTDIR)\.\FileFormat\DICOM\Value.obj \
$(OUTDIR)\.\FileFormat\DICOM\Window.obj \
$(OUTDIR)\.\FileFormat\FrontFlow\BoundaryData.obj \
$(OUTDIR)\.\FileFormat\FrontFlow\Data.obj \
$(OUTDIR)\.\FileFormat\FrontFlow\DataSet.obj \
$(OUTDIR)\.\FileFormat\FrontFlow\File.obj \
$(OUTDIR)\.\FileFormat\FrontFlow\FlowData.obj \
$(OUTDIR)\.\FileFormat\FrontFlow\GFData.obj \
$(OUTDIR)\.\FileFormat\FrontFlow\MeshData.obj \
$(OUTDIR)\.\FileFormat\FrontSTR\FrontSTR.obj \
$(OUTDIR)\.\FileFormat\FrontSTR\MeshData.obj \
$(OUTDIR)\.\FileFormat\FrontSTR\ResultData.obj \
$(OUTDIR)\.\FileFormat\GIS\Area.obj \
$(OUTDIR)\.\FileFormat\GIS\Degree.obj \
$(OUTDIR)\.\FileFormat\GIS\GSIMesh.obj \
$(OUTDIR)\.\FileFormat\GIS\Gis.obj \
$(OUTDIR)\.\FileFormat\GIS\Mesh.obj \
$(OUTDIR)\.\FileFormat\GIS\Point.obj \
$(OUTDIR)\.\FileFormat\GIS\USGSMesh.obj \
$(OUTDIR)\.\FileFormat\GrADS\DSet.obj \
$(OUTDIR)\.\FileFormat\GrADS\DataDescriptorFile.obj \
$(OUTDIR)\.\FileFormat\GrADS\GrADS.obj \
$(OUTDIR)\.\FileFormat\GrADS\GriddedBinaryDataFile.obj \
$(OUTDIR)\.\FileFormat\GrADS\Options.obj \
$(OUTDIR)\.\FileFormat\GrADS\TDef.obj \
$(OUTDIR)\.\FileFormat\GrADS\Title.obj \
$(OUTDIR)\.\FileFormat\GrADS\Undef.obj \
$(OUTDIR)\.\FileFormat\GrADS\Vars.obj \
$(OUTDIR)\.\FileFormat\GrADS\XYZDef.obj \
$(OUTDIR)\.\FileFormat\KVSML\CellTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\ColorMapTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\ColorTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\ColumnTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\ConnectionTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\CoordTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\DataArrayTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\DataReader.obj \
$(OUTDIR)\.\FileFormat\KVSML\DataValueTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\DataWriter.obj \
$(OUTDIR)\.\FileFormat\KVSML\ImageObjectTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\KVSMLObjectImage.obj \
$(OUTDIR)\.\FileFormat\KVSML\KVSMLObjectLine.obj \
$(OUTDIR)\.\FileFormat\KVSML\KVSMLObjectPoint.obj \
$(OUTDIR)\.\FileFormat\KVSML\KVSMLObjectPolygon.obj \
$(OUTDIR)\.\FileFormat\KVSML\KVSMLObjectStructuredVolume.obj \
$(OUTDIR)\.\FileFormat\KVSML\KVSMLObjectTable.obj \
$(OUTDIR)\.\FileFormat\KVSML\KVSMLObjectUnstructuredVolume.obj \
$(OUTDIR)\.\FileFormat\KVSML\KVSMLTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\KVSMLTransferFunction.obj \
$(OUTDIR)\.\FileFormat\KVSML\LineObjectTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\LineTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\NodeTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\NormalTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\ObjectTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\OpacityMapTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\OpacityTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\PixelTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\PointObjectTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\PolygonObjectTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\PolygonTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\SizeTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\StructuredVolumeObjectTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\TableObjectTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\TagBase.obj \
$(OUTDIR)\.\FileFormat\KVSML\TransferFunctionTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\UnstructuredVolumeObjectTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\ValueTag.obj \
$(OUTDIR)\.\FileFormat\KVSML\VertexTag.obj \
$(OUTDIR)\.\FileFormat\PLY\Ply.obj \
$(OUTDIR)\.\FileFormat\PLY\PlyFile.obj \
$(OUTDIR)\.\FileFormat\PNM\Header.obj \
$(OUTDIR)\.\FileFormat\PNM\Pbm.obj \
$(OUTDIR)\.\FileFormat\PNM\Pgm.obj \
$(OUTDIR)\.\FileFormat\PNM\Ppm.obj \
$(OUTDIR)\.\FileFormat\STL\Stl.obj \
$(OUTDIR)\.\FileFormat\TIFF\Entry.obj \
$(OUTDIR)\.\FileFormat\TIFF\Header.obj \
$(OUTDIR)\.\FileFormat\TIFF\ImageFileDirectory.obj \
$(OUTDIR)\.\FileFormat\TIFF\Tag.obj \
$(OUTDIR)\.\FileFormat\TIFF\TagDictionary.obj \
$(OUTDIR)\.\FileFormat\TIFF\Tiff.obj \
$(OUTDIR)\.\FileFormat\XML\TinyXML.obj \
$(OUTDIR)\.\FileFormat\XML\XMLComment.obj \
$(OUTDIR)\.\FileFormat\XML\XMLDeclaration.obj \
$(OUTDIR)\.\FileFormat\XML\XMLDocument.obj \
$(OUTDIR)\.\FileFormat\XML\XMLElement.obj \
$(OUTDIR)\.\FileFormat\XML\XMLNode.obj \
$(OUTDIR)\.\Image\BitImage.obj \
$(OUTDIR)\.\Image\ColorImage.obj \
$(OUTDIR)\.\Image\GrayImage.obj \
$(OUTDIR)\.\Image\HSVColor.obj \
$(OUTDIR)\.\Image\ImageBase.obj \
$(OUTDIR)\.\Image\RGBAColor.obj \
$(OUTDIR)\.\Image\RGBColor.obj \
$(OUTDIR)\.\Matrix\FrustumMatrix44.obj \
$(OUTDIR)\.\Matrix\LookAtMatrix44.obj \
$(OUTDIR)\.\Matrix\Matrix.obj \
$(OUTDIR)\.\Matrix\Matrix22.obj \
$(OUTDIR)\.\Matrix\Matrix33.obj \
$(OUTDIR)\.\Matrix\Matrix44.obj \
$(OUTDIR)\.\Matrix\OrthogonalMatrix44.obj \
$(OUTDIR)\.\Matrix\PerspectiveMatrix44.obj \
$(OUTDIR)\.\Matrix\RotationMatrix33.obj \
$(OUTDIR)\.\Matrix\ScalingMatrix33.obj \
$(OUTDIR)\.\Matrix\Vector.obj \
$(OUTDIR)\.\Matrix\Vector2.obj \
$(OUTDIR)\.\Matrix\Vector3.obj \
$(OUTDIR)\.\Matrix\Vector4.obj \
$(OUTDIR)\.\Matrix\ViewingMatrix44.obj \
$(OUTDIR)\.\Network\Acceptor.obj \
$(OUTDIR)\.\Network\Connector.obj \
$(OUTDIR)\.\Network\HttpConnector.obj \
$(OUTDIR)\.\Network\HttpRequestHeader.obj \
$(OUTDIR)\.\Network\IPAddress.obj \
$(OUTDIR)\.\Network\MessageBlock.obj \
$(OUTDIR)\.\Network\Socket.obj \
$(OUTDIR)\.\Network\SocketAddress.obj \
$(OUTDIR)\.\Network\SocketSelector.obj \
$(OUTDIR)\.\Network\SocketTimer.obj \
$(OUTDIR)\.\Network\TCPBarrier.obj \
$(OUTDIR)\.\Network\TCPBarrierServer.obj \
$(OUTDIR)\.\Network\TCPServer.obj \
$(OUTDIR)\.\Network\TCPSocket.obj \
$(OUTDIR)\.\Network\Url.obj \
$(OUTDIR)\.\Numeric\AdaptiveKMeans.obj \
$(OUTDIR)\.\Numeric\EigenDecomposer.obj \
$(OUTDIR)\.\Numeric\FastKMeans.obj \
$(OUTDIR)\.\Numeric\GaussEliminationSolver.obj \
$(OUTDIR)\.\Numeric\KMeans.obj \
$(OUTDIR)\.\Numeric\LUDecomposer.obj \
$(OUTDIR)\.\Numeric\LUSolver.obj \
$(OUTDIR)\.\Numeric\MersenneTwister.obj \
$(OUTDIR)\.\Numeric\QRDecomposer.obj \
$(OUTDIR)\.\Numeric\QRSolver.obj \
$(OUTDIR)\.\Numeric\Quaternion.obj \
$(OUTDIR)\.\Numeric\ResponseSurface.obj \
$(OUTDIR)\.\Numeric\SVDecomposer.obj \
$(OUTDIR)\.\Numeric\SVSolver.obj \
$(OUTDIR)\.\Numeric\Xorshift128.obj \
$(OUTDIR)\.\OpenGL\BufferObject.obj \
$(OUTDIR)\.\OpenGL\DisplayList.obj \
$(OUTDIR)\.\OpenGL\FragmentShader.obj \
$(OUTDIR)\.\OpenGL\FrameBuffer.obj \
$(OUTDIR)\.\OpenGL\FrameBufferObject.obj \
$(OUTDIR)\.\OpenGL\GL.obj \
$(OUTDIR)\.\OpenGL\GeometryShader.obj \
$(OUTDIR)\.\OpenGL\IndexBufferObject.obj \
$(OUTDIR)\.\OpenGL\OpenGL.obj \
$(OUTDIR)\.\OpenGL\PixelPackBufferObject.obj \
$(OUTDIR)\.\OpenGL\PixelUnpackBufferObject.obj \
$(OUTDIR)\.\OpenGL\ProgramObject.obj \
$(OUTDIR)\.\OpenGL\RenderBuffer.obj \
$(OUTDIR)\.\OpenGL\ShaderObject.obj \
$(OUTDIR)\.\OpenGL\ShaderSource.obj \
$(OUTDIR)\.\OpenGL\Texture.obj \
$(OUTDIR)\.\OpenGL\Texture1D.obj \
$(OUTDIR)\.\OpenGL\Texture2D.obj \
$(OUTDIR)\.\OpenGL\Texture3D.obj \
$(OUTDIR)\.\OpenGL\TextureBinder.obj \
$(OUTDIR)\.\OpenGL\TextureRectangle.obj \
$(OUTDIR)\.\OpenGL\VertexBufferObject.obj \
$(OUTDIR)\.\OpenGL\VertexShader.obj \
$(OUTDIR)\.\Thread\Condition.obj \
$(OUTDIR)\.\Thread\Mutex.obj \
$(OUTDIR)\.\Thread\MutexLocker.obj \
$(OUTDIR)\.\Thread\ReadLocker.obj \
$(OUTDIR)\.\Thread\ReadWriteLock.obj \
$(OUTDIR)\.\Thread\Semaphore.obj \
$(OUTDIR)\.\Thread\Thread.obj \
$(OUTDIR)\.\Thread\WriteLocker.obj \
$(OUTDIR)\.\Utility\AnyValue.obj \
$(OUTDIR)\.\Utility\AnyValueArray.obj \
$(OUTDIR)\.\Utility\AnyValueTable.obj \
$(OUTDIR)\.\Utility\BitArray.obj \
$(OUTDIR)\.\Utility\CommandLine.obj \
$(OUTDIR)\.\Utility\Date.obj \
$(OUTDIR)\.\Utility\Directory.obj \
$(OUTDIR)\.\Utility\FastTokenizer.obj \
$(OUTDIR)\.\Utility\File.obj \
$(OUTDIR)\.\Utility\Indent.obj \
$(OUTDIR)\.\Utility\MemoryTracer.obj \
$(OUTDIR)\.\Utility\Message.obj \
$(OUTDIR)\.\Utility\Program.obj \
$(OUTDIR)\.\Utility\Range.obj \
$(OUTDIR)\.\Utility\ReferenceCounter.obj \
$(OUTDIR)\.\Utility\String.obj \
$(OUTDIR)\.\Utility\SystemInformation.obj \
$(OUTDIR)\.\Utility\Time.obj \
$(OUTDIR)\.\Utility\Tokenizer.obj \
$(OUTDIR)\.\Utility\Type.obj \
$(OUTDIR)\.\Utility\Value.obj \
$(OUTDIR)\.\Utility\ValueArray.obj \
$(OUTDIR)\.\Utility\ValueTable.obj \
$(OUTDIR)\.\Visualization\Data\HydrogenVolumeData.obj \
$(OUTDIR)\.\Visualization\Data\TornadoVolumeData.obj \
$(OUTDIR)\.\Visualization\Event\EventBase.obj \
$(OUTDIR)\.\Visualization\Event\EventHandler.obj \
$(OUTDIR)\.\Visualization\Event\EventListener.obj \
$(OUTDIR)\.\Visualization\Event\IdleEventListener.obj \
$(OUTDIR)\.\Visualization\Event\InitializeEvent.obj \
$(OUTDIR)\.\Visualization\Event\InitializeEventListener.obj \
$(OUTDIR)\.\Visualization\Event\KeyEvent.obj \
$(OUTDIR)\.\Visualization\Event\KeyPressEventListener.obj \
$(OUTDIR)\.\Visualization\Event\MouseDoubleClickEventListener.obj \
$(OUTDIR)\.\Visualization\Event\MouseEvent.obj \
$(OUTDIR)\.\Visualization\Event\MouseMoveEventListener.obj \
$(OUTDIR)\.\Visualization\Event\MousePressEventListener.obj \
$(OUTDIR)\.\Visualization\Event\MouseReleaseEventListener.obj \
$(OUTDIR)\.\Visualization\Event\PaintEvent.obj \
$(OUTDIR)\.\Visualization\Event\PaintEventListener.obj \
$(OUTDIR)\.\Visualization\Event\ResizeEvent.obj \
$(OUTDIR)\.\Visualization\Event\ResizeEventListener.obj \
$(OUTDIR)\.\Visualization\Event\ScreenCaptureEvent.obj \
$(OUTDIR)\.\Visualization\Event\TargetChangeEvent.obj \
$(OUTDIR)\.\Visualization\Event\TimeEvent.obj \
$(OUTDIR)\.\Visualization\Event\TimerEventListener.obj \
$(OUTDIR)\.\Visualization\Event\WheelEvent.obj \
$(OUTDIR)\.\Visualization\Event\WheelEventListener.obj \
$(OUTDIR)\.\Visualization\Exporter\LineExporter.obj \
$(OUTDIR)\.\Visualization\Exporter\PointExporter.obj \
$(OUTDIR)\.\Visualization\Exporter\PolygonExporter.obj \
$(OUTDIR)\.\Visualization\Exporter\StructuredVolumeExporter.obj \
$(OUTDIR)\.\Visualization\Exporter\UnstructuredVolumeExporter.obj \
$(OUTDIR)\.\Visualization\Filter\KMeansClustering.obj \
$(OUTDIR)\.\Visualization\Filter\LineIntegralConvolution.obj \
$(OUTDIR)\.\Visualization\Filter\StructuredVectorToScalar.obj \
$(OUTDIR)\.\Visualization\Filter\TetrahedraToTetrahedra.obj \
$(OUTDIR)\.\Visualization\Filter\Tubeline.obj \
$(OUTDIR)\.\Visualization\Filter\UnstructuredVectorToScalar.obj \
$(OUTDIR)\.\Visualization\Importer\ImageImporter.obj \
$(OUTDIR)\.\Visualization\Importer\LineImporter.obj \
$(OUTDIR)\.\Visualization\Importer\PointImporter.obj \
$(OUTDIR)\.\Visualization\Importer\PolygonImporter.obj \
$(OUTDIR)\.\Visualization\Importer\StructuredVolumeImporter.obj \
$(OUTDIR)\.\Visualization\Importer\TableImporter.obj \
$(OUTDIR)\.\Visualization\Importer\UnstructuredVolumeImporter.obj \
$(OUTDIR)\.\Visualization\Mapper\Cell.obj \
$(OUTDIR)\.\Visualization\Mapper\CellAdjacencyGraph.obj \
$(OUTDIR)\.\Visualization\Mapper\CellAdjacencyGraphLocator.obj \
$(OUTDIR)\.\Visualization\Mapper\CellBase.obj \
$(OUTDIR)\.\Visualization\Mapper\CellByCellLayeredSampling.obj \
$(OUTDIR)\.\Visualization\Mapper\CellByCellMetropolisSampling.obj \
$(OUTDIR)\.\Visualization\Mapper\CellByCellRejectionSampling.obj \
$(OUTDIR)\.\Visualization\Mapper\CellByCellUniformSampling.obj \
$(OUTDIR)\.\Visualization\Mapper\CellLocator.obj \
$(OUTDIR)\.\Visualization\Mapper\CellTree.obj \
$(OUTDIR)\.\Visualization\Mapper\CellTreeLocator.obj \
$(OUTDIR)\.\Visualization\Mapper\ColorMap.obj \
$(OUTDIR)\.\Visualization\Mapper\ExternalFaces.obj \
$(OUTDIR)\.\Visualization\Mapper\ExtractEdges.obj \
$(OUTDIR)\.\Visualization\Mapper\ExtractVertices.obj \
$(OUTDIR)\.\Visualization\Mapper\FrequencyTable.obj \
$(OUTDIR)\.\Visualization\Mapper\HexahedralCell.obj \
$(OUTDIR)\.\Visualization\Mapper\HitAndMissSampling.obj \
$(OUTDIR)\.\Visualization\Mapper\Isosurface.obj \
$(OUTDIR)\.\Visualization\Mapper\MapperBase.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingCubes.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingCubesTable.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingHexahedra.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingHexahedraTable.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingPrism.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingPrismTable.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingPyramid.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingPyramidTable.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingTetrahedra.obj \
$(OUTDIR)\.\Visualization\Mapper\MarchingTetrahedraTable.obj \
$(OUTDIR)\.\Visualization\Mapper\MetropolisSampling.obj \
$(OUTDIR)\.\Visualization\Mapper\OpacityMap.obj \
$(OUTDIR)\.\Visualization\Mapper\OrthoSlice.obj \
$(OUTDIR)\.\Visualization\Mapper\PrismaticCell.obj \
$(OUTDIR)\.\Visualization\Mapper\PyramidalCell.obj \
$(OUTDIR)\.\Visualization\Mapper\QuadraticHexahedralCell.obj \
$(OUTDIR)\.\Visualization\Mapper\QuadraticTetrahedralCell.obj \
$(OUTDIR)\.\Visualization\Mapper\RGBFormulae.obj \
$(OUTDIR)\.\Visualization\Mapper\SlicePlane.obj \
$(OUTDIR)\.\Visualization\Mapper\Streamline.obj \
$(OUTDIR)\.\Visualization\Mapper\StreamlineBase.obj \
$(OUTDIR)\.\Visualization\Mapper\TetrahedralCell.obj \
$(OUTDIR)\.\Visualization\Mapper\TransferFunction.obj \
$(OUTDIR)\.\Visualization\Object\GeometryObjectBase.obj \
$(OUTDIR)\.\Visualization\Object\ImageObject.obj \
$(OUTDIR)\.\Visualization\Object\LineObject.obj \
$(OUTDIR)\.\Visualization\Object\ObjectBase.obj \
$(OUTDIR)\.\Visualization\Object\PointObject.obj \
$(OUTDIR)\.\Visualization\Object\PolygonObject.obj \
$(OUTDIR)\.\Visualization\Object\StructuredVolumeObject.obj \
$(OUTDIR)\.\Visualization\Object\TableObject.obj \
$(OUTDIR)\.\Visualization\Object\UnstructuredVolumeObject.obj \
$(OUTDIR)\.\Visualization\Object\VolumeObjectBase.obj \
$(OUTDIR)\.\Visualization\Pipeline\ObjectImporter.obj \
$(OUTDIR)\.\Visualization\Pipeline\PipelineModule.obj \
$(OUTDIR)\.\Visualization\Pipeline\VisualizationPipeline.obj \
$(OUTDIR)\.\Visualization\Renderer\ArrowGlyph.obj \
$(OUTDIR)\.\Visualization\Renderer\Bounds.obj \
$(OUTDIR)\.\Visualization\Renderer\DiamondGlyph.obj \
$(OUTDIR)\.\Visualization\Renderer\EnsembleAverageBuffer.obj \
$(OUTDIR)\.\Visualization\Renderer\GlyphBase.obj \
$(OUTDIR)\.\Visualization\Renderer\HAVSVolumeRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\ImageRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\LineRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\LineRendererGLSL.obj \
$(OUTDIR)\.\Visualization\Renderer\ParallelCoordinatesRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\ParticleBasedRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\ParticleBasedRendererGLSL.obj \
$(OUTDIR)\.\Visualization\Renderer\ParticleBasedRendererRITS.obj \
$(OUTDIR)\.\Visualization\Renderer\ParticleBuffer.obj \
$(OUTDIR)\.\Visualization\Renderer\ParticleBufferAccumulator.obj \
$(OUTDIR)\.\Visualization\Renderer\ParticleBufferCompositor.obj \
$(OUTDIR)\.\Visualization\Renderer\PointRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\PointRendererGLSL.obj \
$(OUTDIR)\.\Visualization\Renderer\PolygonRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\PolygonRendererGLSL.obj \
$(OUTDIR)\.\Visualization\Renderer\PreIntegrationTable3D.obj \
$(OUTDIR)\.\Visualization\Renderer\ProjectedTetrahedraTable.obj \
$(OUTDIR)\.\Visualization\Renderer\Ray.obj \
$(OUTDIR)\.\Visualization\Renderer\RayCastingRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\RayCastingRendererGLSL.obj \
$(OUTDIR)\.\Visualization\Renderer\ScatterPlotMatrixRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\ScatterPlotRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\Shader.obj \
$(OUTDIR)\.\Visualization\Renderer\ShadingParameter.obj \
$(OUTDIR)\.\Visualization\Renderer\SphereGlyph.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticLineRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticMultipleTetrahedraCompositor.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticMultipleTetrahedraRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticMultivariateTetrahedraRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticPointRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticPolygonRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticRendererBase.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticRenderingCompositor.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticRenderingEngine.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticTetrahedraRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\StochasticUniformGridRenderer.obj \
$(OUTDIR)\.\Visualization\Renderer\VolumeRayIntersector.obj \
$(OUTDIR)\.\Visualization\Renderer\VolumeRendererBase.obj \
$(OUTDIR)\.\Visualization\Viewer\ApplicationBase.obj \
$(OUTDIR)\.\Visualization\Viewer\Background.obj \
$(OUTDIR)\.\Visualization\Viewer\Camera.obj \
$(OUTDIR)\.\Visualization\Viewer\CameraCoordinate.obj \
$(OUTDIR)\.\Visualization\Viewer\DisplayFormat.obj \
$(OUTDIR)\.\Visualization\Viewer\IDManager.obj \
$(OUTDIR)\.\Visualization\Viewer\Light.obj \
$(OUTDIR)\.\Visualization\Viewer\Material.obj \
$(OUTDIR)\.\Visualization\Viewer\Mouse.obj \
$(OUTDIR)\.\Visualization\Viewer\NormalizedDeviceCoordinate.obj \
$(OUTDIR)\.\Visualization\Viewer\ObjectCoordinate.obj \
$(OUTDIR)\.\Visualization\Viewer\ObjectManager.obj \
$(OUTDIR)\.\Visualization\Viewer\RendererManager.obj \
$(OUTDIR)\.\Visualization\Viewer\Scene.obj \
$(OUTDIR)\.\Visualization\Viewer\ScreenBase.obj \
$(OUTDIR)\.\Visualization\Viewer\Trackball.obj \
$(OUTDIR)\.\Visualization\Viewer\WindowCoordinate.obj \
$(OUTDIR)\.\Visualization\Viewer\WorldCoordinate.obj \
$(OUTDIR)\.\Visualization\Viewer\Xform.obj \
$(OUTDIR)\.\Visualization\Viewer\XformControl.obj \



{.\Visualization\Viewer\}.cpp{$(OUTDIR)\.\Visualization\Viewer\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Viewer $(MKDIR) $(OUTDIR)\.\Visualization\Viewer
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Viewer\ @<<
$<
<<

{.\Visualization\Renderer\}.cpp{$(OUTDIR)\.\Visualization\Renderer\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Renderer $(MKDIR) $(OUTDIR)\.\Visualization\Renderer
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Renderer\ @<<
$<
<<

{.\Visualization\Pipeline\}.cpp{$(OUTDIR)\.\Visualization\Pipeline\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Pipeline $(MKDIR) $(OUTDIR)\.\Visualization\Pipeline
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Pipeline\ @<<
$<
<<

{.\Visualization\Object\}.cpp{$(OUTDIR)\.\Visualization\Object\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Object $(MKDIR) $(OUTDIR)\.\Visualization\Object
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Object\ @<<
$<
<<

{.\Visualization\Mapper\}.cpp{$(OUTDIR)\.\Visualization\Mapper\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Mapper $(MKDIR) $(OUTDIR)\.\Visualization\Mapper
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Mapper\ @<<
$<
<<

{.\Visualization\Importer\}.cpp{$(OUTDIR)\.\Visualization\Importer\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Importer $(MKDIR) $(OUTDIR)\.\Visualization\Importer
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Importer\ @<<
$<
<<

{.\Visualization\Filter\}.cpp{$(OUTDIR)\.\Visualization\Filter\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Filter $(MKDIR) $(OUTDIR)\.\Visualization\Filter
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Filter\ @<<
$<
<<

{.\Visualization\Exporter\}.cpp{$(OUTDIR)\.\Visualization\Exporter\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Exporter $(MKDIR) $(OUTDIR)\.\Visualization\Exporter
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Exporter\ @<<
$<
<<

{.\Visualization\Event\}.cpp{$(OUTDIR)\.\Visualization\Event\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Event $(MKDIR) $(OUTDIR)\.\Visualization\Event
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Event\ @<<
$<
<<

{.\Visualization\Data\}.cpp{$(OUTDIR)\.\Visualization\Data\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Visualization\Data $(MKDIR) $(OUTDIR)\.\Visualization\Data
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Visualization\Data\ @<<
$<
<<

{.\Utility\}.cpp{$(OUTDIR)\.\Utility\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Utility $(MKDIR) $(OUTDIR)\.\Utility
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Utility\ @<<
$<
<<

{.\Thread\}.cpp{$(OUTDIR)\.\Thread\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Thread $(MKDIR) $(OUTDIR)\.\Thread
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Thread\ @<<
$<
<<

{.\OpenGL\}.cpp{$(OUTDIR)\.\OpenGL\}.obj::
	IF NOT EXIST $(OUTDIR)\.\OpenGL $(MKDIR) $(OUTDIR)\.\OpenGL
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\OpenGL\ @<<
$<
<<

{.\Numeric\}.cpp{$(OUTDIR)\.\Numeric\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Numeric $(MKDIR) $(OUTDIR)\.\Numeric
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Numeric\ @<<
$<
<<

{.\Network\}.cpp{$(OUTDIR)\.\Network\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Network $(MKDIR) $(OUTDIR)\.\Network
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Network\ @<<
$<
<<

{.\Matrix\}.cpp{$(OUTDIR)\.\Matrix\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Matrix $(MKDIR) $(OUTDIR)\.\Matrix
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Matrix\ @<<
$<
<<

{.\Image\}.cpp{$(OUTDIR)\.\Image\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Image $(MKDIR) $(OUTDIR)\.\Image
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Image\ @<<
$<
<<

{.\FileFormat\XML\}.cpp{$(OUTDIR)\.\FileFormat\XML\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\XML $(MKDIR) $(OUTDIR)\.\FileFormat\XML
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\XML\ @<<
$<
<<

{.\FileFormat\TIFF\}.cpp{$(OUTDIR)\.\FileFormat\TIFF\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\TIFF $(MKDIR) $(OUTDIR)\.\FileFormat\TIFF
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\TIFF\ @<<
$<
<<

{.\FileFormat\STL\}.cpp{$(OUTDIR)\.\FileFormat\STL\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\STL $(MKDIR) $(OUTDIR)\.\FileFormat\STL
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\STL\ @<<
$<
<<

{.\FileFormat\PNM\}.cpp{$(OUTDIR)\.\FileFormat\PNM\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\PNM $(MKDIR) $(OUTDIR)\.\FileFormat\PNM
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\PNM\ @<<
$<
<<

{.\FileFormat\PLY\}.cpp{$(OUTDIR)\.\FileFormat\PLY\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\PLY $(MKDIR) $(OUTDIR)\.\FileFormat\PLY
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\PLY\ @<<
$<
<<

{.\FileFormat\KVSML\}.cpp{$(OUTDIR)\.\FileFormat\KVSML\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\KVSML $(MKDIR) $(OUTDIR)\.\FileFormat\KVSML
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\KVSML\ @<<
$<
<<

{.\FileFormat\GrADS\}.cpp{$(OUTDIR)\.\FileFormat\GrADS\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\GrADS $(MKDIR) $(OUTDIR)\.\FileFormat\GrADS
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\GrADS\ @<<
$<
<<

{.\FileFormat\GIS\}.cpp{$(OUTDIR)\.\FileFormat\GIS\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\GIS $(MKDIR) $(OUTDIR)\.\FileFormat\GIS
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\GIS\ @<<
$<
<<

{.\FileFormat\FrontSTR\}.cpp{$(OUTDIR)\.\FileFormat\FrontSTR\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\FrontSTR $(MKDIR) $(OUTDIR)\.\FileFormat\FrontSTR
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\FrontSTR\ @<<
$<
<<

{.\FileFormat\FrontFlow\}.cpp{$(OUTDIR)\.\FileFormat\FrontFlow\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\FrontFlow $(MKDIR) $(OUTDIR)\.\FileFormat\FrontFlow
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\FrontFlow\ @<<
$<
<<

{.\FileFormat\DICOM\}.cpp{$(OUTDIR)\.\FileFormat\DICOM\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\DICOM $(MKDIR) $(OUTDIR)\.\FileFormat\DICOM
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\DICOM\ @<<
$<
<<

{.\FileFormat\CSV\}.cpp{$(OUTDIR)\.\FileFormat\CSV\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\CSV $(MKDIR) $(OUTDIR)\.\FileFormat\CSV
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\CSV\ @<<
$<
<<

{.\FileFormat\BMP\}.cpp{$(OUTDIR)\.\FileFormat\BMP\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\BMP $(MKDIR) $(OUTDIR)\.\FileFormat\BMP
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\BMP\ @<<
$<
<<

{.\FileFormat\AVSUCD\}.cpp{$(OUTDIR)\.\FileFormat\AVSUCD\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\AVSUCD $(MKDIR) $(OUTDIR)\.\FileFormat\AVSUCD
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\AVSUCD\ @<<
$<
<<

{.\FileFormat\AVSField\}.cpp{$(OUTDIR)\.\FileFormat\AVSField\}.obj::
	IF NOT EXIST $(OUTDIR)\.\FileFormat\AVSField $(MKDIR) $(OUTDIR)\.\FileFormat\AVSField
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\FileFormat\AVSField\ @<<
$<
<<


install::
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat
	$(INSTALL) .\FileFormat\*.h $(INSTALL_DIR)\include\Core\.\FileFormat
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\AVSField $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\AVSField
	$(INSTALL) .\FileFormat\AVSField\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\AVSField
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\AVSUCD $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\AVSUCD
	$(INSTALL) .\FileFormat\AVSUCD\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\AVSUCD
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\BMP $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\BMP
	$(INSTALL) .\FileFormat\BMP\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\BMP
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\CSV $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\CSV
	$(INSTALL) .\FileFormat\CSV\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\CSV
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\DICOM $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\DICOM
	$(INSTALL) .\FileFormat\DICOM\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\DICOM
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\FrontFlow $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\FrontFlow
	$(INSTALL) .\FileFormat\FrontFlow\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\FrontFlow
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\FrontSTR $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\FrontSTR
	$(INSTALL) .\FileFormat\FrontSTR\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\FrontSTR
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\GIS $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\GIS
	$(INSTALL) .\FileFormat\GIS\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\GIS
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\GrADS $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\GrADS
	$(INSTALL) .\FileFormat\GrADS\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\GrADS
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\KVSML $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\KVSML
	$(INSTALL) .\FileFormat\KVSML\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\KVSML
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\PLY $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\PLY
	$(INSTALL) .\FileFormat\PLY\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\PLY
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\PNM $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\PNM
	$(INSTALL) .\FileFormat\PNM\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\PNM
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\STL $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\STL
	$(INSTALL) .\FileFormat\STL\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\STL
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\TIFF $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\TIFF
	$(INSTALL) .\FileFormat\TIFF\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\TIFF
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\FileFormat\XML $(MKDIR) $(INSTALL_DIR)\include\Core\.\FileFormat\XML
	$(INSTALL) .\FileFormat\XML\*.h $(INSTALL_DIR)\include\Core\.\FileFormat\XML
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Image $(MKDIR) $(INSTALL_DIR)\include\Core\.\Image
	$(INSTALL) .\Image\*.h $(INSTALL_DIR)\include\Core\.\Image
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Matrix $(MKDIR) $(INSTALL_DIR)\include\Core\.\Matrix
	$(INSTALL) .\Matrix\*.h $(INSTALL_DIR)\include\Core\.\Matrix
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Network $(MKDIR) $(INSTALL_DIR)\include\Core\.\Network
	$(INSTALL) .\Network\*.h $(INSTALL_DIR)\include\Core\.\Network
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Numeric $(MKDIR) $(INSTALL_DIR)\include\Core\.\Numeric
	$(INSTALL) .\Numeric\*.h $(INSTALL_DIR)\include\Core\.\Numeric
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\OpenGL $(MKDIR) $(INSTALL_DIR)\include\Core\.\OpenGL
	$(INSTALL) .\OpenGL\*.h $(INSTALL_DIR)\include\Core\.\OpenGL
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Thread $(MKDIR) $(INSTALL_DIR)\include\Core\.\Thread
	$(INSTALL) .\Thread\*.h $(INSTALL_DIR)\include\Core\.\Thread
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Utility $(MKDIR) $(INSTALL_DIR)\include\Core\.\Utility
	$(INSTALL) .\Utility\*.h $(INSTALL_DIR)\include\Core\.\Utility
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization
	$(INSTALL) .\Visualization\*.h $(INSTALL_DIR)\include\Core\.\Visualization
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Data $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Data
	$(INSTALL) .\Visualization\Data\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Data
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Event $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Event
	$(INSTALL) .\Visualization\Event\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Event
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Exporter $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Exporter
	$(INSTALL) .\Visualization\Exporter\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Exporter
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Filter $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Filter
	$(INSTALL) .\Visualization\Filter\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Filter
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Importer $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Importer
	$(INSTALL) .\Visualization\Importer\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Importer
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Mapper $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Mapper
	$(INSTALL) .\Visualization\Mapper\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Mapper
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Object $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Object
	$(INSTALL) .\Visualization\Object\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Object
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Pipeline $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Pipeline
	$(INSTALL) .\Visualization\Pipeline\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Pipeline
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Renderer $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Renderer
	$(INSTALL) .\Visualization\Renderer\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Renderer
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Shader $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Shader
	$(INSTALL) .\Visualization\Shader\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Shader
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Viewer $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Viewer
	$(INSTALL) .\Visualization\Viewer\*.h $(INSTALL_DIR)\include\Core\.\Visualization\Viewer
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Shader $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Shader
	$(INSTALL) .\Visualization\Shader\*.vert $(INSTALL_DIR)\include\Core\.\Visualization\Shader
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Shader $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Shader
	$(INSTALL) .\Visualization\Shader\*.geom $(INSTALL_DIR)\include\Core\.\Visualization\Shader
	IF NOT EXIST $(INSTALL_DIR)\include\Core\.\Visualization\Shader $(MKDIR) $(INSTALL_DIR)\include\Core\.\Visualization\Shader
	$(INSTALL) .\Visualization\Shader\*.frag $(INSTALL_DIR)\include\Core\.\Visualization\Shader
