#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS = \
$(OUTDIR)\.\Call.obj \
$(OUTDIR)\.\Viewer\Config.obj \
$(OUTDIR)\.\Viewer\Context.obj \
$(OUTDIR)\.\Viewer\Display.obj \
$(OUTDIR)\.\Viewer\Screen.obj \
$(OUTDIR)\.\Viewer\ScreenBase.obj \
$(OUTDIR)\.\Viewer\Surface.obj \



{.\Viewer\}.cpp{$(OUTDIR)\.\Viewer\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Viewer $(MKDIR) $(OUTDIR)\.\Viewer
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Viewer\ @<<
$<
<<

{.\}.cpp{$(OUTDIR)\.\}.obj::
	IF NOT EXIST $(OUTDIR)\. $(MKDIR) $(OUTDIR)\.
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\ @<<
$<
<<


install::
	IF NOT EXIST $(INSTALL_DIR)\include\SupportEGL\. $(MKDIR) $(INSTALL_DIR)\include\SupportEGL\.
	$(INSTALL) .\*.h $(INSTALL_DIR)\include\SupportEGL\.
	IF NOT EXIST $(INSTALL_DIR)\include\SupportEGL\.\Viewer $(MKDIR) $(INSTALL_DIR)\include\SupportEGL\.\Viewer
	$(INSTALL) .\Viewer\*.h $(INSTALL_DIR)\include\SupportEGL\.\Viewer
