# - Try to find kvs
# Once done this will define
# KVS_FOUND
# KVS_CORE_LIBRARY
# KVS_SUPPORTGLUT_(LIBRARY|INCLUDE_DIR)
# KVS_SUPPORTQT_(LIBRARY|INCLUDE_DIR)
# KVS_SUPPORTOPENCV_(LIBRARY|INCLUDE_DIR)

find_package(PkgConfig)
find_path(KVS_INCLUDE_DIR NAMES kvs)
find_library(KVS_CORE_LIBRARY NAMES kvsCore)

if(KVS_INCLUDE_DIR)
	MESSAGE(STATUS "Found KVS: ${KVS_INCLUDE_DIR}/kvs")
	SET(KVS_FOUND True)
else(KVS_INCLUDE_DIR)
	MESSAGE(STATUS "Not Found: KVS")
	SET(KVS_FOUND False)
endif(KVS_INCLUDE_DIR)