# - Try to find kvs
# Once done this will define
# KVS_SUPPORTGLUT_(LIBRARY|INCLUDE_DIR)

find_package(PkgConfig)
find_library(KVS_SUPPORTGLUT_LIBRARY NAMES kvsSupportGLUT)

if(KVS_SUPPORTGLUT_LIBRARY)
	MESSAGE(STATUS "Found kvsSupportGLUT: ${KVS_SUPPORTGLUT_LIBRARY}")
	MESSAGE(STATUS "KVS_SUPPORTGLUT_INCLUDE_DIR: ${KVS_SUPPORTGLUT_INCLUDE_DIR}")
else(KVS_SUPPORTGLUT_LIBRARY)
	MESSAGE(STATUS "Not Found: kvsSupportGLUT")	
	SET(KVS_FOUND FALSE)
endif(KVS_SUPPORTGLUT_LIBRARY)