#!/bin/sh
VOLUME_SIZE=128
IMAGE_SIZE=1024
NNODES=4

OUTPUT_COLOR_IMAGE=0
OUTPUT_ALPHA_IMAGE=0
OUTPUT_DEPTH_IMAGE=0

mpirun --oversubscribe -n $NNODES ./ImageComposition $VOLUME_SIZE $IMAGE_SIZE $OUTPUT_COLOR_IMAGE $OUTPUT_ALPHA_IMAGE $OUTPUT_DEPTH_IMAGE
