#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS := \
$(OUTDIR)/./Array.o \
$(OUTDIR)/./Bool.o \
$(OUTDIR)/./Callable.o \
$(OUTDIR)/./Dict.o \
$(OUTDIR)/./Float.o \
$(OUTDIR)/./Int.o \
$(OUTDIR)/./Interpreter.o \
$(OUTDIR)/./List.o \
$(OUTDIR)/./Module.o \
$(OUTDIR)/./Object.o \
$(OUTDIR)/./Python.o \
$(OUTDIR)/./String.o \
$(OUTDIR)/./Table.o \
$(OUTDIR)/./Tuple.o \



$(OUTDIR)/./%.o: ./%.cpp ./%.h
	$(MKDIR) $(OUTDIR)
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<


install::
	$(MKDIR) $(INSTALL_DIR)/include/SupportPython/.
	$(INSTALL) ./*.h $(INSTALL_DIR)/include/SupportPython/.
