#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS = \
$(OUTDIR)\.\Array.obj \
$(OUTDIR)\.\Bool.obj \
$(OUTDIR)\.\Callable.obj \
$(OUTDIR)\.\Dict.obj \
$(OUTDIR)\.\Float.obj \
$(OUTDIR)\.\Int.obj \
$(OUTDIR)\.\Interpreter.obj \
$(OUTDIR)\.\List.obj \
$(OUTDIR)\.\Module.obj \
$(OUTDIR)\.\Object.obj \
$(OUTDIR)\.\Python.obj \
$(OUTDIR)\.\String.obj \
$(OUTDIR)\.\Table.obj \
$(OUTDIR)\.\Tuple.obj \



{.\}.cpp{$(OUTDIR)\.\}.obj::
	IF NOT EXIST $(OUTDIR)\. $(MKDIR) $(OUTDIR)\.
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\ @<<
$<
<<


install::
	IF NOT EXIST $(INSTALL_DIR)\include\SupportPython\. $(MKDIR) $(INSTALL_DIR)\include\SupportPython\.
	$(INSTALL) .\*.h $(INSTALL_DIR)\include\SupportPython\.
