#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS = \
$(OUTDIR)\.\Object\MovieObject.obj \
$(OUTDIR)\.\Object\VideoObject.obj \
$(OUTDIR)\.\Renderer\MovieRenderer.obj \
$(OUTDIR)\.\Renderer\SphericalMovieRenderer.obj \
$(OUTDIR)\.\Renderer\VideoRenderer.obj \
$(OUTDIR)\.\Viewer\CaptureDevice.obj \
$(OUTDIR)\.\Viewer\Window.obj \



{.\Viewer\}.cpp{$(OUTDIR)\.\Viewer\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Viewer $(MKDIR) $(OUTDIR)\.\Viewer
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Viewer\ @<<
$<
<<

{.\Renderer\}.cpp{$(OUTDIR)\.\Renderer\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Renderer $(MKDIR) $(OUTDIR)\.\Renderer
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Renderer\ @<<
$<
<<

{.\Object\}.cpp{$(OUTDIR)\.\Object\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Object $(MKDIR) $(OUTDIR)\.\Object
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Object\ @<<
$<
<<


install::
	IF NOT EXIST $(INSTALL_DIR)\include\SupportOpenCV\. $(MKDIR) $(INSTALL_DIR)\include\SupportOpenCV\.
	$(INSTALL) .\*.h $(INSTALL_DIR)\include\SupportOpenCV\.
	IF NOT EXIST $(INSTALL_DIR)\include\SupportOpenCV\.\Object $(MKDIR) $(INSTALL_DIR)\include\SupportOpenCV\.\Object
	$(INSTALL) .\Object\*.h $(INSTALL_DIR)\include\SupportOpenCV\.\Object
	IF NOT EXIST $(INSTALL_DIR)\include\SupportOpenCV\.\Renderer $(MKDIR) $(INSTALL_DIR)\include\SupportOpenCV\.\Renderer
	$(INSTALL) .\Renderer\*.h $(INSTALL_DIR)\include\SupportOpenCV\.\Renderer
	IF NOT EXIST $(INSTALL_DIR)\include\SupportOpenCV\.\Viewer $(MKDIR) $(INSTALL_DIR)\include\SupportOpenCV\.\Viewer
	$(INSTALL) .\Viewer\*.h $(INSTALL_DIR)\include\SupportOpenCV\.\Viewer
