#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS := \
$(OUTDIR)/./Communicator.o \
$(OUTDIR)/./Environment.o \
$(OUTDIR)/./MPICall.o \
$(OUTDIR)/./Request.o \
$(OUTDIR)/./Window.o \



$(OUTDIR)/./%.o: ./%.cpp ./%.h
	$(MKDIR) $(OUTDIR)
	$(MPICPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<


install::
	$(MKDIR) $(INSTALL_DIR)/include/SupportMPI/.
	$(INSTALL) ./*.h $(INSTALL_DIR)/include/SupportMPI/.
