#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS = \
$(OUTDIR)\.\Communicator.obj \
$(OUTDIR)\.\Environment.obj \
$(OUTDIR)\.\MPICall.obj \
$(OUTDIR)\.\Request.obj \
$(OUTDIR)\.\Window.obj \



{.\}.cpp{$(OUTDIR)\.\}.obj::
	IF NOT EXIST $(OUTDIR)\. $(MKDIR) $(OUTDIR)\.
	$(MPICPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\ @<<
$<
<<


install::
	IF NOT EXIST $(INSTALL_DIR)\include\SupportMPI\. $(MKDIR) $(INSTALL_DIR)\include\SupportMPI\.
	$(INSTALL) .\*.h $(INSTALL_DIR)\include\SupportMPI\.
