#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS = \
$(OUTDIR)\.\Viewer\Context.obj \
$(OUTDIR)\.\Viewer\Screen.obj \
$(OUTDIR)\.\Viewer\ScreenBase.obj \
$(OUTDIR)\.\Viewer\Surface.obj \



{.\Viewer\}.cpp{$(OUTDIR)\.\Viewer\}.obj::
	IF NOT EXIST $(OUTDIR)\.\Viewer $(MKDIR) $(OUTDIR)\.\Viewer
	$(CPP) /c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) /Fo$(OUTDIR)\.\Viewer\ @<<
$<
<<


install::
	IF NOT EXIST $(INSTALL_DIR)\include\SupportOSMesa\. $(MKDIR) $(INSTALL_DIR)\include\SupportOSMesa\.
	$(INSTALL) .\*.h $(INSTALL_DIR)\include\SupportOSMesa\.
	IF NOT EXIST $(INSTALL_DIR)\include\SupportOSMesa\.\Viewer $(MKDIR) $(INSTALL_DIR)\include\SupportOSMesa\.\Viewer
	$(INSTALL) .\Viewer\*.h $(INSTALL_DIR)\include\SupportOSMesa\.\Viewer
