#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS := \
$(OUTDIR)/./Viewer/Context.o \
$(OUTDIR)/./Viewer/Screen.o \
$(OUTDIR)/./Viewer/ScreenBase.o \
$(OUTDIR)/./Viewer/Surface.o \



$(OUTDIR)/./Viewer/%.o: ./Viewer/%.cpp ./Viewer/%.h
	$(MKDIR) $(OUTDIR)/./Viewer
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<


install::
	$(MKDIR) $(INSTALL_DIR)/include/SupportOSMesa/.
	$(INSTALL) ./*.h $(INSTALL_DIR)/include/SupportOSMesa/.
	$(MKDIR) $(INSTALL_DIR)/include/SupportOSMesa/./Viewer
	$(INSTALL) ./Viewer/*.h $(INSTALL_DIR)/include/SupportOSMesa/./Viewer
