#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS := \
$(OUTDIR)/./Renderer/Axis2D.o \
$(OUTDIR)/./Renderer/Axis2DMatrix.o \
$(OUTDIR)/./Renderer/Axis3D.o \
$(OUTDIR)/./Renderer/ParallelAxis.o \
$(OUTDIR)/./Viewer/Application.o \
$(OUTDIR)/./Viewer/Histogram.o \
$(OUTDIR)/./Viewer/LegendBar.o \
$(OUTDIR)/./Viewer/OrientationAxis.o \
$(OUTDIR)/./Viewer/Screen.o \
$(OUTDIR)/./Viewer/ScreenBase.o \
$(OUTDIR)/./Viewer/Text.o \
$(OUTDIR)/./Viewer/Timer.o \
$(OUTDIR)/./Viewer/TransferFunctionEditor.o \
$(OUTDIR)/./Widget/CheckBox.o \
$(OUTDIR)/./Widget/CheckBoxGroup.o \
$(OUTDIR)/./Widget/ColorMapPalette.o \
$(OUTDIR)/./Widget/ColorPalette.o \
$(OUTDIR)/./Widget/Label.o \
$(OUTDIR)/./Widget/OpacityMapPalette.o \
$(OUTDIR)/./Widget/PushButton.o \
$(OUTDIR)/./Widget/RadioButton.o \
$(OUTDIR)/./Widget/RadioButtonGroup.o \
$(OUTDIR)/./Widget/Rectangle.o \
$(OUTDIR)/./Widget/Slider.o \
$(OUTDIR)/./Widget/WidgetBase.o \



$(OUTDIR)/./Widget/%.o: ./Widget/%.cpp ./Widget/%.h
	$(MKDIR) $(OUTDIR)/./Widget
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<

$(OUTDIR)/./Viewer/%.o: ./Viewer/%.cpp ./Viewer/%.h
	$(MKDIR) $(OUTDIR)/./Viewer
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<

$(OUTDIR)/./Renderer/%.o: ./Renderer/%.cpp ./Renderer/%.h
	$(MKDIR) $(OUTDIR)/./Renderer
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<


install::
	$(MKDIR) $(INSTALL_DIR)/include/SupportGLUT/.
	$(INSTALL) ./*.h $(INSTALL_DIR)/include/SupportGLUT/.
	$(MKDIR) $(INSTALL_DIR)/include/SupportGLUT/./Renderer
	$(INSTALL) ./Renderer/*.h $(INSTALL_DIR)/include/SupportGLUT/./Renderer
	$(MKDIR) $(INSTALL_DIR)/include/SupportGLUT/./Viewer
	$(INSTALL) ./Viewer/*.h $(INSTALL_DIR)/include/SupportGLUT/./Viewer
	$(MKDIR) $(INSTALL_DIR)/include/SupportGLUT/./Widget
	$(INSTALL) ./Widget/*.h $(INSTALL_DIR)/include/SupportGLUT/./Widget
