#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS := \
$(OUTDIR)/./AvCpp/audioresampler.o \
$(OUTDIR)/./AvCpp/averror.o \
$(OUTDIR)/./AvCpp/avtime.o \
$(OUTDIR)/./AvCpp/avutils.o \
$(OUTDIR)/./AvCpp/codec.o \
$(OUTDIR)/./AvCpp/codeccontext.o \
$(OUTDIR)/./AvCpp/dictionary.o \
$(OUTDIR)/./AvCpp/format.o \
$(OUTDIR)/./AvCpp/formatcontext.o \
$(OUTDIR)/./AvCpp/frame.o \
$(OUTDIR)/./AvCpp/packet.o \
$(OUTDIR)/./AvCpp/pixelformat.o \
$(OUTDIR)/./AvCpp/rational.o \
$(OUTDIR)/./AvCpp/rect.o \
$(OUTDIR)/./AvCpp/sampleformat.o \
$(OUTDIR)/./AvCpp/stream.o \
$(OUTDIR)/./AvCpp/timestamp.o \
$(OUTDIR)/./AvCpp/videorescaler.o \
$(OUTDIR)/./Demuxer.o \
$(OUTDIR)/./Object/MovieObject.o \
$(OUTDIR)/./Renderer/MovieRenderer.o \
$(OUTDIR)/./Renderer/SphericalMovieRenderer.o \



$(OUTDIR)/./Renderer/%.o: ./Renderer/%.cpp ./Renderer/%.h
	$(MKDIR) $(OUTDIR)/./Renderer
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<

$(OUTDIR)/./Object/%.o: ./Object/%.cpp ./Object/%.h
	$(MKDIR) $(OUTDIR)/./Object
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<

$(OUTDIR)/./AvCpp/%.o: ./AvCpp/%.cpp ./AvCpp/%.h
	$(MKDIR) $(OUTDIR)/./AvCpp
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<

$(OUTDIR)/./%.o: ./%.cpp ./%.h
	$(MKDIR) $(OUTDIR)
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<


install::
	$(MKDIR) $(INSTALL_DIR)/include/SupportFFmpeg/.
	$(INSTALL) ./*.h $(INSTALL_DIR)/include/SupportFFmpeg/.
	$(MKDIR) $(INSTALL_DIR)/include/SupportFFmpeg/./AvCpp
	$(INSTALL) ./AvCpp/*.h $(INSTALL_DIR)/include/SupportFFmpeg/./AvCpp
	$(MKDIR) $(INSTALL_DIR)/include/SupportFFmpeg/./Object
	$(INSTALL) ./Object/*.h $(INSTALL_DIR)/include/SupportFFmpeg/./Object
	$(MKDIR) $(INSTALL_DIR)/include/SupportFFmpeg/./Renderer
	$(INSTALL) ./Renderer/*.h $(INSTALL_DIR)/include/SupportFFmpeg/./Renderer
