#pragma once

extern "C" {
#include <libavutil/version.h>
#include <libavcodec/version.h>
#include <libavformat/version.h>
#include <libavdevice/version.h>
#include <libavfilter/version.h>
#include <libswscale/version.h>
#include <libswresample/version.h>
}

#ifndef AVCPP_CXX_STANDARD
#  if defined(_MSVC_LANG)
#    if _MSVC_LANG >= 202002L
#      define AVCPP_CXX_STANDARD 20
#    elif _MSVC_LANG >= 201703L
#      define AVCPP_CXX_STANDARD 17
#    else
#      define AVCPP_CXX_STANDARD 14
#    endif
#  elif defined(__cplusplus)
#    if __cplusplus >= 202002L
#      define AVCPP_CXX_STANDARD 20
#    elif __cplusplus >= 201703L
#      define AVCPP_CXX_STANDARD 17
#    else
#      define AVCPP_CXX_STANDARD 14
#    endif
#  else
#    define AVCPP_CXX_STANDARD 17
#  endif
#endif

#define AVCPP_HAS_PKT_SIDE_DATA   (AVCPP_CXX_STANDARD >= 20)
#define AVCPP_HAS_FRAME_SIDE_DATA (AVCPP_CXX_STANDARD >= 20)

#define AVCPP_AVCODEC_VERSION_MAJOR LIBAVCODEC_VERSION_MAJOR
#define AVCPP_AVCODEC_VERSION_MINOR LIBAVCODEC_VERSION_MINOR
#define AVCPP_AVCODEC_VERSION_PATCH LIBAVCODEC_VERSION_MICRO
#define AVCPP_AVCODEC_VERSION_INT   LIBAVCODEC_VERSION_INT
#define AVCPP_HAS_AVCODEC 1

#define AVCPP_AVFORMAT_VERSION_MAJOR LIBAVFORMAT_VERSION_MAJOR
#define AVCPP_AVFORMAT_VERSION_MINOR LIBAVFORMAT_VERSION_MINOR
#define AVCPP_AVFORMAT_VERSION_PATCH LIBAVFORMAT_VERSION_MICRO
#define AVCPP_AVFORMAT_VERSION_INT   LIBAVFORMAT_VERSION_INT
#define AVCPP_HAS_AVFORMAT 1

#define AVCPP_AVUTIL_VERSION_MAJOR LIBAVUTIL_VERSION_MAJOR
#define AVCPP_AVUTIL_VERSION_MINOR LIBAVUTIL_VERSION_MINOR
#define AVCPP_AVUTIL_VERSION_PATCH LIBAVUTIL_VERSION_MICRO
#define AVCPP_AVUTIL_VERSION_INT   LIBAVUTIL_VERSION_INT
#define AVCPP_HAS_AVUTIL 1

#define AVCPP_AVDEVICE_VERSION_MAJOR LIBAVDEVICE_VERSION_MAJOR
#define AVCPP_AVDEVICE_VERSION_MINOR LIBAVDEVICE_VERSION_MINOR
#define AVCPP_AVDEVICE_VERSION_PATCH LIBAVDEVICE_VERSION_MICRO
#define AVCPP_AVDEVICE_VERSION_INT   LIBAVDEVICE_VERSION_INT
#define AVCPP_HAS_AVDEVICE 1

#define AVCPP_AVFILTER_VERSION_MAJOR LIBAVFILTER_VERSION_MAJOR
#define AVCPP_AVFILTER_VERSION_MINOR LIBAVFILTER_VERSION_MINOR
#define AVCPP_AVFILTER_VERSION_PATCH LIBAVFILTER_VERSION_MICRO
#define AVCPP_AVFILTER_VERSION_INT   LIBAVFILTER_VERSION_INT
#define AVCPP_HAS_AVFILTER 1

#define AVCPP_SWSCALE_VERSION_MAJOR LIBSWSCALE_VERSION_MAJOR
#define AVCPP_SWSCALE_VERSION_MINOR LIBSWSCALE_VERSION_MINOR
#define AVCPP_SWSCALE_VERSION_PATCH LIBSWSCALE_VERSION_MICRO
#define AVCPP_SWSCALE_VERSION_INT   LIBSWSCALE_VERSION_INT
#define AVCPP_HAS_AVSWSCALE 1
#define AVCPP_HAS_SWSCALE 1

#define AVCPP_SWRESAMPLE_VERSION_MAJOR LIBSWRESAMPLE_VERSION_MAJOR
#define AVCPP_SWRESAMPLE_VERSION_MINOR LIBSWRESAMPLE_VERSION_MINOR
#define AVCPP_SWRESAMPLE_VERSION_PATCH LIBSWRESAMPLE_VERSION_MICRO
#define AVCPP_SWRESAMPLE_VERSION_INT   LIBSWRESAMPLE_VERSION_INT
#define AVCPP_AVSWRESAMPLE_VERSION_INT LIBSWRESAMPLE_VERSION_INT
#define AVCPP_HAS_AVSWRESAMPLE 1
#define AVCPP_HAS_SWRESAMPLE 1
