#  DON'T EDIT THIS FILE.
#  THIS IS GENERATED BY "Configuration/configure_BuildRule.py".


OBJECTS := \
$(OUTDIR)/./DriverAPI/Context.o \
$(OUTDIR)/./DriverAPI/Device.o \
$(OUTDIR)/./DriverAPI/DriverAPI.o \
$(OUTDIR)/./DriverAPI/ErrorString.o \
$(OUTDIR)/./DriverAPI/Initialization.o \
$(OUTDIR)/./RuntimeAPI/Device.o \
$(OUTDIR)/./RuntimeAPI/ErrorString.o \
$(OUTDIR)/./RuntimeAPI/RuntimeAPI.o \



$(OUTDIR)/./RuntimeAPI/%.o: ./RuntimeAPI/%.cpp ./RuntimeAPI/%.h
	$(MKDIR) $(OUTDIR)/./RuntimeAPI
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<

$(OUTDIR)/./DriverAPI/%.o: ./DriverAPI/%.cpp ./DriverAPI/%.h
	$(MKDIR) $(OUTDIR)/./DriverAPI
	$(CPP) -c $(CPPFLAGS) $(DEFINITIONS) $(INCLUDE_PATH) -o $@ $<


install::
	$(MKDIR) $(INSTALL_DIR)/include/SupportCUDA/.
	$(INSTALL) ./*.h $(INSTALL_DIR)/include/SupportCUDA/.
	$(MKDIR) $(INSTALL_DIR)/include/SupportCUDA/./DriverAPI
	$(INSTALL) ./DriverAPI/*.h $(INSTALL_DIR)/include/SupportCUDA/./DriverAPI
	$(MKDIR) $(INSTALL_DIR)/include/SupportCUDA/./RuntimeAPI
	$(INSTALL) ./RuntimeAPI/*.h $(INSTALL_DIR)/include/SupportCUDA/./RuntimeAPI
